app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_Postman:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\PostmanController'
    name_prefix: api_1_ #naming collision
	
app_parcel_order:
    type: rest
    prefix: /v2
    resource: 'AppBundle\Controller\ParcelOrderController'
    name_prefix: api_2_
	
app_ParcelOrder:
    type: rest
    prefix: /v3
    resource: 'AppBundle\Controller\ParcelOrderController'
    name_prefix: api_3_ #naming collision